databases:
  - name: nico-api-db
    databaseName: nico_api
    user: nico

services:
  - type: web
    name: nico-api
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nico-api-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
